import {describe,it,expect} from 'vitest';
import {createInitialGame,addWave,stepGame,steer,sweptCollision,MAX_SPEED} from './simulation';
const run=()=>{const game=createInitialGame();game.phase='running';game.traffic=[];game.nextWaveAt=1e9;return game;};
const advance=(game,input,seconds)=>{for(let i=0;i<seconds*60;i++)stepGame(game,input,1/60);};
describe('original side-view pedal driving',()=>{
 it('starts stationary with stationary scenery and wheels until gas is held',()=>{const g=createInitialGame(),before=structuredClone(g);advance(g,{},5);expect(g).toEqual(before);stepGame(g,{gas:true},.05);expect(g.phase).toBe('running');expect(g.speed).toBeGreaterThan(0);});
 it('gas accelerates, release coasts to rest, and brake stops faster without reversing',()=>{const g=run();advance(g,{gas:true},2);expect(g.speed).toBeCloseTo(76);const coast=structuredClone(g),brake=structuredClone(g);advance(coast,{},.5);advance(brake,{brake:true},.5);expect(brake.speed).toBeLessThan(coast.speed);advance(coast,{},10);advance(brake,{brake:true,gas:true},10);expect(coast.speed).toBe(0);expect(brake.speed).toBe(0);const scroll=coast.scroll,wheel=coast.wheelAngle;advance(coast,{},2);expect(coast.scroll).toBe(scroll);expect(coast.wheelAngle).toBe(wheel);});
 it('holds the speed limit without boost drain or automatic cruise',()=>{const g=run();advance(g,{gas:true},30);expect(g.speed).toBe(MAX_SPEED);advance(g,{},1);expect(g.speed).toBeLessThan(MAX_SPEED);});
 it('does not advance while paused or crashed',()=>{for(const phase of ['paused','crashed']){const g=run();g.phase=phase;const before=structuredClone(g);advance(g,{gas:true},5);expect(g).toEqual(before);}});
 it('uses three smooth bounded lanes',()=>{const g=run();steer(g,-1);steer(g,-1);expect(g.targetLane).toBe(0);stepGame(g,{},.05);expect(g.lane).toBeGreaterThan(0);advance(g,{},1);expect(g.lane).toBe(0);steer(g,1);steer(g,1);steer(g,1);expect(g.targetLane).toBe(2);});
 it('leaves a reachable adjacent gap in 10000 seeded waves',()=>{const g=run();g.distance=10000;for(let i=0;i<10000;i++){const w=addWave(g,20);expect(g.traffic.length).toBeLessThan(3);expect(g.traffic.some(c=>c.lane===w.safeLane)).toBe(false);expect(Math.abs(w.safeLane-w.previousSafe)).toBeLessThanOrEqual(1);g.traffic=[];}});
 it('reproduces traffic from a seed',()=>{expect(createInitialGame(99)).toEqual(createInitialGame(99));expect(createInitialGame(99).traffic).not.toEqual(createInitialGame(42).traffic);});
 it('detects swept contact including lane transitions, but not separated lanes',()=>{expect(sweptCollision(1,1,10,-10,1)).toBe(true);expect(sweptCollision(0,0,10,-10,1)).toBe(false);expect(sweptCollision(0,1,3,-3,1)).toBe(true);});
 it('damages once per contact and grants recovery before a three-impact finish',()=>{const g=run();g.speed=100;const hit=()=>{g.traffic=[{id:1,lane:1,z:4.3,hit:false}];stepGame(g,{gas:true},.05);};hit();expect(g.health).toBe(66);expect(g.phase).toBe('running');advance(g,{gas:true},.5);expect(g.health).toBe(66);g.traffic=[];advance(g,{},2);hit();expect(g.health).toBe(32);g.traffic=[];advance(g,{},2);hit();expect(g.phase).toBe('crashed');expect(g.health).toBe(0);expect(g.speed).toBe(0);});
 it('awards each clean overtake once, never a collided car',()=>{const g=run();g.speed=150;g.lane=0;g.targetLane=0;g.traffic=[{id:0,lane:1,z:-5.19,passed:false},{id:1,lane:2,z:-5.19,hit:true,passed:false}];stepGame(g,{gas:true},.05);expect(g.passes).toBe(1);expect(g.bonus).toBe(50);advance(g,{gas:true},1);expect(g.passes).toBe(1);});
 it('runs twenty minutes with bounded traffic, unbroken safe gaps and increasing score',()=>{const g=createInitialGame();let max=0,score=0;for(let i=0;i<24000;i++){const next=g.traffic.filter(c=>c.z>5).sort((a,b)=>a.z-b.z)[0];if(next&&next.z<11){const blocked=new Set(g.traffic.filter(c=>c.wave===next.wave).map(c=>c.lane));if(blocked.has(g.targetLane)){const safe=[0,1,2].filter(l=>!blocked.has(l)).sort((a,b)=>Math.abs(a-g.targetLane)-Math.abs(b-g.targetLane))[0];steer(g,Math.sign(safe-g.targetLane));}}stepGame(g,{gas:true},.05);max=Math.max(max,g.traffic.length);expect(g.phase).toBe('running');expect(g.health).toBe(100);expect(g.score).toBeGreaterThanOrEqual(score);score=g.score;}expect(g.distance).toBeGreaterThan(70000);expect(g.passes).toBeGreaterThan(100);expect(max).toBeLessThan(15);});
});
