import React from 'react';
import {fireEvent,render,screen,act,cleanup} from '@testing-library/react';
import {vi,beforeEach,afterEach,it,expect} from 'vitest';
import App from './App';
let callback,time;
beforeEach(()=>{time=0;window.localStorage.clear();vi.stubGlobal('requestAnimationFrame',vi.fn(cb=>{callback=cb;return 1;}));vi.stubGlobal('cancelAnimationFrame',vi.fn());});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const frame=()=>act(()=>callback(time+=16));
it('shows original car and pedals at rest with no blocking intro',()=>{render(<App/>);expect(screen.getByRole('heading',{name:'Pedal Rush'})).toBeInTheDocument();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();for(const name of ['Gas','Brake','Move up a lane','Move down a lane'])expect(screen.getByRole('button',{name})).toBeInTheDocument();expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-phase','ready');fireEvent.keyDown(window,{key:' '});frame();frame();expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-phase','running');});
it('releases gas on focus loss and resumes the same lane',()=>{render(<App/>);fireEvent.keyDown(window,{key:' '});frame();fireEvent.keyDown(window,{key:'ArrowDown'});fireEvent.blur(window);expect(screen.getByRole('button',{name:'Gas'})).toHaveAttribute('aria-pressed','false');expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-phase','paused');fireEvent.click(screen.getByRole('button',{name:'Resume run'}));expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-lane','3');});
it('pointer cancel and capture loss both release pedals',()=>{render(<App/>);const pedal=screen.getByRole('button',{name:'Gas'});fireEvent.pointerDown(pedal,{pointerId:1});expect(pedal).toHaveAttribute('aria-pressed','true');fireEvent.pointerCancel(pedal,{pointerId:1});expect(pedal).toHaveAttribute('aria-pressed','false');fireEvent.pointerDown(pedal,{pointerId:2});fireEvent.lostPointerCapture(pedal,{pointerId:2});expect(pedal).toHaveAttribute('aria-pressed','false');});
it('new run clears speed, score and lane but retains a saved record',()=>{window.localStorage.setItem('pedal-rush:best-score','1200');render(<App/>);fireEvent.keyDown(window,{key:' '});frame();fireEvent.keyDown(window,{key:'ArrowDown'});fireEvent.keyDown(window,{key:'p'});fireEvent.click(screen.getByRole('button',{name:'Start a new run'}));expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-phase','ready');expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-lane','2');expect(screen.getByTestId('score')).toHaveTextContent('0');expect(screen.getByTestId('best')).toHaveTextContent((1200).toLocaleString());});

it('changes lane on a second pointer while the gas remains held without a duplicate click',()=>{render(<App/>);const gas=screen.getByRole('button',{name:'Gas'}),down=screen.getByRole('button',{name:'Move down a lane'});fireEvent.pointerDown(gas,{pointerId:1});fireEvent.pointerDown(down,{pointerId:2});fireEvent.click(down,{detail:1});expect(screen.getByLabelText('Pedal Rush game')).toHaveAttribute('data-lane','3');expect(gas).toHaveAttribute('aria-pressed','true');});
