import React from "react";
import { fireEvent, render, screen, act } from "@testing-library/react";
import { vi } from "vitest";
vi.mock("./game/scene",()=>({createRoadScene:()=>({render:vi.fn(),dispose:vi.fn()})}));
import App from "./App";
it("offers an explicit start and accessible gas/brake/steering controls",()=>{render(<App/>);expect(screen.getByRole("heading",{name:/Pedal Rush/})).toBeInTheDocument();for(const name of ["Gas","Brake","Move left","Move right"])expect(screen.getByRole("button",{name})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/START RUN/}));expect(screen.getByLabelText("Pedal Rush game")).toHaveAttribute("data-phase","running");});
it("releases held gas and pauses on focus loss; resume retains the lane",()=>{render(<App/>);fireEvent.keyDown(window,{key:"Enter"});fireEvent.keyDown(window,{key:"ArrowRight"});fireEvent.keyDown(window,{key:"ArrowUp"});expect(screen.getByRole("button",{name:"Gas"})).toHaveAttribute("aria-pressed","true");fireEvent.blur(window);expect(screen.getByLabelText("Pedal Rush game")).toHaveAttribute("data-phase","paused");expect(screen.getByRole("button",{name:"Gas"})).toHaveAttribute("aria-pressed","false");fireEvent.click(screen.getByRole("button",{name:/RESUME RUN/}));expect(screen.getByText(/LANE 3 \/ 4/)).toBeInTheDocument();});
it("restart resets controls, score and lane while preserving best",()=>{window.localStorage.setItem("pedal-rush:coastline-best","1200");render(<App/>);fireEvent.keyDown(window,{key:"Enter"});fireEvent.keyDown(window,{key:"d"});fireEvent.keyDown(window,{key:"p"});fireEvent.click(screen.getByRole("button",{name:"Start a new run"}));expect(screen.getByText(/LANE 2 \/ 4/)).toBeInTheDocument();expect(screen.getByTestId("score")).toHaveTextContent("0");expect(screen.getByText((1200).toLocaleString())).toBeInTheDocument();});
it("pointer cancellation releases a held pedal",()=>{render(<App/>);fireEvent.keyDown(window,{key:"Enter"});const gas=screen.getByRole("button",{name:"Gas"});fireEvent.pointerDown(gas,{pointerId:1});expect(gas).toHaveAttribute("aria-pressed","true");fireEvent.pointerCancel(gas,{pointerId:1});expect(gas).toHaveAttribute("aria-pressed","false");});

